version: '3'
services:
  uberlimb-front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8344:8344"
    image: ${LIMB_REGISTRY:-registry.jetbrains.team/p/genart/uberlimb}/kascade-streamlit:${IMAGE_VERSION:-latest}
